#!/usr/bin/bash
export DISPLAY=:0

DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
export DBUS_SESSION_BUS_ADDRESS
export XDG_RUNTIME_DIR="/run/user/1000"


battery_level=`acpi -b | grep -P -o '[0-9]+(?=%)'`
if on_ac_power; then
    if [ $battery_level -ge 85 ]; then
        notify-send --urgency=CRITICAL "Battery Overcharge" "Level: ${battery_level}% "
        paplay /usr/share/sounds/freedesktop/stereo/suspend-error.oga
    fi
fi
#else
#    if [ $battery_level -le 20 ]; then
#        notify-send --urgency=CRITICAL "Battery Low" "Level: ${battery_level}%"
#        paplay /usr/share/sounds/freedesktop/stereo/suspend-error.oga
#    fi
#fi
