#!/usr/bin/bash

query="https://www.google.com/search?client=firefox-b-d&q="

for arg in "$@"
do
	query="$query+$arg"
done

tilix --quake # comment this line if you wish don't use tilix in quake mode
# this will basically hide the tilix quake prompt

xdg-open "$query"
# echo "$query"
